[Details]
  Icon = "Icon.png"
  Name = "TBlockMC"
  ID = "com.tblockmc.launcher"
  Build = 56

[Development]
  HelperText = "This binary was built with debug symbols"

[Release]
  HelperText = "This binary was built without debug symbols"

[Source]
  Repo = "https://github.com/tblockmc/launcher"
