name: TBlockMC Release Binary
on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]

permissions:
  contents: write

# TODO: use matrix
jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true

  build_macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install Fyne tool
        run: go install fyne.io/tools/cmd/fyne@latest
      
      - name: Set version
        run: |
          TAG=${{ github.event.release.tag_name }} 
          echo "VERSION=${TAG#v:-dev-build}" >> $GITHUB_ENV
      
      - name: Package
        run: |
          fyne package -os darwin --app-version $VERSION --icon Icon.png --release
          codesign --force --deep --preserve-metadata=entitlements,requirements,flags,runtime --sign - "./TBlockMC.app/Contents/MacOS/tblock-launcher"
      
      - name: Create zip
        run: zip --symlinks -r TBlockMC-mac-arm64.zip TBlockMC.app/
      
      - name: Upload zip archive
        uses: actions/upload-artifact@v4
        with:
          name: TBlockMC-mac-arm64.zip
          path: TBlockMC-mac-arm64.zip

      - name: Release mac app
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.create_release.outputs.tag-name }}
          files: TBlockMC-mac-arm64.zip

  build_windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        path-type: inherit
        update: true
        install: >-
          make
          wget
          zip
          p7zip
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Install Dependencies
      run: >
        pacman -Syu &&
        pacman --noconfirm -S mingw-w64-x86_64-toolchain mingw-w64-x86_64-mpv

    - name: Install Fyne tool
      run: go install fyne.io/tools/cmd/fyne@latest

    - name: Set version
      run: |
        TAG=${{ github.event.release.tag_name }} 
        echo "VERSION=${TAG#v:-dev-build}" >> $GITHUB_ENV
      
    - name: Package
      run: |
         CGO_LDFLAGS="-H=windowsgui" fyne package -os windows --icon Icon.png --executable tblockmc.exe --release

    - name: Create zip
      run: zip TBlockMC-windows-x64.zip tblockmc.exe

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: TBlockMC-windows-x64.exe
        path: tblockmc.exe

    - name: Upload zip
      uses: actions/upload-artifact@v4
      with:
        name: TBlockMC-windows-x64.zip
        path: TBlockMC-windows-x64.zip
          
    - name: Release windows executable
      if: github.ref_type == 'tag'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ needs.create_release.outputs.tag-name }}
        files: TBlockMC-windows-x64.zip
